env:
  global:
    - secure: FrpokPre8jJglSfghynadjitBvWc8RJ26EUR3waoITAE8v0QVQ1mMc07yfHCVhweHysg3BKlB5PKAD2eom5dsux2O7qwGQhiwOBwqZY+t0sDV4snXQWF8oko4Xi0v+SnZA5V+4jlEIj98sP2sj4ge6ZS7bCZ9bjpwkIUpoI+D0s=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
script:
  - rustc src/lib.rs
  - rustdoc src/lib.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh