env:
  global:
    - secure: wIMcZ6nwvjGNw8qdMObEoiWYoKNkkE7bwyEV/IvWDOxvtbec/4ItKfmAwBdrw5L/fkMeSpSWnXokICSwUs2HRdymWUizvS2dm1wbOLfEq6pJfB4MZ+dHzXAioKXakJLn1uIRG+18qo/kDgv8KL7haW++ssdTXN2Zy+qsWRNbveE=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/rust/rust-nightly/lib
  - rustc -v
script:
  - cargo build
  - rustdoc src/rustic.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh