env:
  global:
    - secure: lsoUaG7+Cb6atKRmBrcA0IKEIwD/EPvgRROZiDq1d/tCs/KBZWUZDfDnwTFEGjC46AFWhLDWOF5uvsM7cbcB1iuOAlxlN3DUpNZ/TFnITXXvKOIFk82TTjtdCmbCYINhmoxy2pFUi+2EMANCaOACA0SOHPv+2eLoeCb/7J5xLmg=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/rust/rust-nightly/lib
script:
  - cargo build
  - rustdoc src/rustic.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh