env:
  global:
    - secure: xKtHW0tjzITnQIblhJczQkR18tglN6vvhKScwK9XSvBE+vRuYEvTiCNm2qDvNFWp2kmU9DLhuCvxvO10Xl2JqOOJDW3OSuMyOPF0/4E5ZJshyvLejDNjPyRxz0VCIfiiZAF8nL+um/hjN25J6tgue7eHbiCZK/rjDf6MS3O1jsQ=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
script:
  - cargo build
  - rustdoc src/rustic.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh