[package]

name = "test-db"
version = "0.1.0"
authors = [ "christophe.pedretti@gmail.com" ]

[[bin]]

name = "test-db" # the name of the executable to generate

[dependencies.rustic]

git = "https://github.com/chris-pe/Rustic.git"